### PR TITLE
chore: adding ggshield-admins team as codeowner

### PR DESCRIPTION
**Pull request by sevbch**
Adding team as codeowners of the repo, to then add a branch protection rule on `main` requesting a review from codeowners.

### CODE REVIEW

**Comment by gg-jonathangriffe** [comment]
I'm not sure we should add ggshield-admin to the codeowners. This group is about 10 people, who from what I understand would be notified for every PR on this repo. WDYT ?

**Comment by sevbch** [comment]
> I'm not sure we should add ggshield-admin to the codeowners. This group is about 10 people, who from what I understand would be notified for every PR on this repo. WDYT ?

I think that maybe there are too many people in the group and we should keep only the team. @agateau-gg , what do you think?

**Comment by sevbch** [comment]
@gg-jonathangriffe I just updated team members, let me know what you think

**Comment by gg-jonathangriffe** [comment]
It seems reasonable now. It's good for me, I'd like to get @salome-voltz 's opinion though.

**Review by salome-voltz — APPROVED** [review]
Works for me, I think it's a good idea

**Pull request merged**
